### ISSUE TITLE
force users to specify epochs in a deme definition

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#133]
So, e.g.
```yaml
demes:
- id: A
  initial_size: 1000
```
Must become
```yaml
demes:
- id: A
  epochs:
  - initial_size: 1000
    end_time: 0
```
@apragsdale and I chatted on slack and we think this might help reduce some potential confusion, and simultaneously simplify the code and/or spec. It comes at the expense of some small additional verbosity in the YAML file.

**Comment by jeromekelleher** [comment]
+1

**Comment by apragsdale** [comment]
I guess that a deme's (and its first epoch's) `start_time` should also be specified if needed in that first epoch, instead of at the deme level. The deme could still have start and end time properties, so that we can check deme time intersections more easily, for example, but the simplified yaml description should always have that info in the epochs.

For example, instead of

```yaml
demes:
- id: A
  start_time: 100
  epochs:
  - initial_size: 2000
    end_time: 0
```

we'd want

```yaml
demes:
- id: A
  epochs:
  - initial_size: 2000
    start_time: 100
    end_time: 0
```
