### ISSUE TITLE
the YAML emitter output is insane

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#155]
E.g. `$ python demes/convert/stdpopsim_.py HomSap OutOfAfrica_3G09`
```yaml
demes:
- epochs:
  - {end_time: 8800.0, initial_size: 7300.0}
  - {end_time: 0, initial_size: 12300.0}
  id: YRI
- ancestors: YRI
  epochs:
  - {end_time: 848.0, initial_size: 2100.0, start_time: 5600.0}
  - {end_time: 0, final_size: 29725.343546388514, initial_size: 1000.0}
  id: CEU
- {ancestors: CEU, end_time: 0, final_size: 54090.331077946525, id: CHB, initial_size: 510.0,
  start_time: 848.0}
description: "The three population Out-of-Africa model from Gutenkunst et al. 2009.\n\
  It describes the ancestral human population in Africa, the out of Africa\nevent,\
  \ and the subsequent European-Asian population split.\nModel parameters are the\
  \ maximum likelihood values of the\nvarious parameters given in Table 1 of Gutenkunst\
  \ et al."
doi: [https://doi.org/10.1371/journal.pgen.1000695]
migrations:
  symmetric:
  - demes: YRI, CEU
    end_time: 848.0
    rate: !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      /Knx0k1iMD8=
  - demes: YRI, CEU
    rate: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      aR1VTRB1/z4=
    start_time: 848.0
  - demes: YRI, CHB
    rate: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      GArYDkbs8z4=
  - demes: CEU, CHB
    rate: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      VOQQcXMqGT8=
time_units: generations
```

This is the default pyyaml-style output (e.g. using `ruamel.yaml.dump()`). It's fixable with newer ruamel API, by explicitly making a `ruamel.yaml.YAML()` object, and calling that object's dump() method.
