### ISSUE TITLE
Make sure we don't allow competing continuous migrations

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/demes-python#166]
Currently, don't think there is a catch to make sure we haven't specified continuous migration between the same source/dest demes that have overlapping time intervals.

E.g., this should result in an error:
```YAML
migrations:
- symmetric:
  - demes: A, B
    rate: 0.01
  - demes: A, B
    rate: 0.02
```
