### ISSUE TITLE
graph equality that ignores epoch and migration subdivisions

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#333]
For epochs the idea would be to make sure the demes are "equal" in the examples below, by checking equality of sizes (and other attributes) over the demes' lifetimes rather than mandating equal numbers of epochs each with equal attribute values. The below example is obvious from visual inspection, but if you do the same with exponentially-changing epochs its less obvious! I haven't really thought through the best way of achieving this. Maybe take the union of each deme's epoch end times and split epochs for each deme at all the time points? Or instead of splitting epochs, just check deme sizes for a few (5?) evenly spaced times in each interval.
```yaml
demes:
- name: A
  epochs:
  - start_size: 100
```
```yaml
demes:
- name: A
  epochs:
  - {start_size: 100, end_time: 50}
  - {start_size: 100, end_time: 0}
```

And similarly for comparing migrations, the following three examples should be "equal". We could just compare resulting migration matrices here.
```yaml
migrations:
 - {demes: [A, B], start_time: 100, end_time: 0, rate: 1e-4}
```
```yaml
migrations:
 - {demes: [A, B], start_time: 100, end_time: 50, rate: 1e-4}
 - {demes: [A, B], start_time: 50, end_time: 0, rate: 1e-4}
```
```yaml
migrations:
 - {source: A, dest: B, start_time: 100, end_time: 0, rate: 1e-4}
 - {source: B, dest: A, start_time: 100, end_time: 0, rate: 1e-4}
```
