### ISSUE TITLE
ms commands combining -es/-ej to produce a pulse of admixture don't work

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#350]
Example of failing command from https://github.com/sriramlab/ArchIE/blob/master/msmodified/readme
`demes ms -I 4 120 118 1 1 -en 0.06 1 0.01 -en 0.0605 1 1 -es 0.0475 1 0.97 -ej 0.0475 5 3 -ej 0.0625 2 1 -en 0.075 3 1 -en 0.078 3 1 -ej 0.225 4 3  -ej 0.325 3 1 -N0 20000`

The problem here is the split immediately followed by a join (`-es 0.0475 1 0.97 -ej 0.0475 5 3`), which is translated into a deme with zero time span. If the time parameter for the join is increased slightly (I appended a 1), we get the following model. There is no other way to produce a pulse-like admixture using ms commands, as far as I can tell. I don't know if this is a widespread method to achieve such a demography, but it might be worth hacking something in to support this use case.

```yaml
time_units: generations
demes:
- name: deme1
  epochs:
  - {end_time: 4840.0, start_size: 20000.0}
  - {end_time: 4800.0, start_size: 200.0}
  - {end_time: 0, start_size: 20000.0}
- name: deme3
  start_time: 26000.0
  ancestors: [deme1]
  epochs:
  - {end_time: 0, start_size: 20000.0}
- name: deme4
  start_time: 18000.0
  ancestors: [deme3]
  epochs:
  - {end_time: 0, start_size: 20000.0}
- name: deme2
  start_time: 5000.0
  ancestors: [deme1]
  epochs:
  - {end_time: 0, start_size: 20000.0}
- name: deme5
  start_time: 3800.7999999999997
  ancestors: [deme3]
  epochs:
  - {end_time: 3800.0, start_size: 20000.0}
pulses:
- {source: deme5, dest: deme1, time: 3800.0, proportion: 0.030000000000000027}
```
