### ISSUE TITLE
Some symmetric migration scenarioes are not simplified

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/demes-python#384]
For graphs with continuous symmetric migration between two demes that do not have equivalent time intervals of existence, `graph.asdict_simplified()` does not collapse the directional migrations into a single symmetric migration specified by `demes` and `rate`. Instead, it remains as asymmetric migrations with `source` and `dest`. Those migrations should be collapsed.

For example, using the Gutenkunst-OOA model:

```python
import demes
g = demes.load("examples/gutenkunst_ooa.yml")
print(g)
```
The migrations print as
```
migrations:
- demes: [YRI, CEU]
  rate: 3e-05
- demes: [YRI, CHB]
  rate: 1.9e-05
- demes: [CEU, CHB]
  rate: 9.6e-05
- {source: YRI, dest: OOA, rate: 0.00025}
- {source: OOA, dest: YRI, end_time: 21200.0, rate: 0.00025}
```

The input file has
```
tail -n 5 examples/gutenkunst_ooa.yaml
```
```
migrations:
- {demes: [YRI, OOA], rate: 25e-5}
- {demes: [YRI, CEU], rate: 3e-5}
- {demes: [YRI, CHB], rate: 1.9e-5}
- {demes: [CEU, CHB], rate: 9.6e-5}
```
