### ISSUE TITLE
simplify multiple pulses with common dest deme into a single pulse

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#390]
Now that we support multiple sources in single pulse event, we should simplify to this when possible.

**Comment by apragsdale** [comment]
Yes - there will be some corner cases that we'll want to be careful about, but this should be straight forward.

By corner cases, I mean the following should _not_ be simplified:

```YAML
pulses:
- time: 1
  sources: ["a"]
  proportions: [0.1]
  dest: "b"
- time: 1
  sources: ["b"]
  proportions: [0.2]
  dest: "d"
- time: 1
  sources: ["c"]
  proportions: [0.3]
  dest: "b"
```

but other scenarios can be, e.g.:
```YAML
pulses:
- time: 1
  sources: ["a"]
  proportions: [0.1]
  dest: "b"
- time: 1
  sources: ["a"]
  proportions: [0.2]
  dest: "d"
- time: 1
  sources: ["c"]
  proportions: [0.3]
  dest: "b"
```
