### ISSUE TITLE
selfing_rate + cloning_rate >=1 should be permitted

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#425]
See https://github.com/popsim-consortium/demes-spec/issues/43#issuecomment-888486763

Test case that should be permitted (but isn't currently):
```yaml
time_units: generations
demes:
- name: A
  epochs:
    - start_size: 100
      selfing_rate: 0.6
      cloning_rate: 0.6
```
