### ISSUE TITLE
Start time for a single demographic scenario

### ISSUE THREAD

**Issue by rmehta1987** [popsim-consortium/demes-python#494]
Hi,

I was wondering if it was possible to have a start time for a single demographic scenario i.e:

```
description: A single population model with epochs of exponential growth and decay.
doi:
  - https://doi.org/10.1038/ng.3015
time_units: generations
demes:
  - name: generic
    epochs:
    - {start_time: 0, start_size: 7156}
    - {start_time: 25,599.98 , start_size: 71560} # 25,599.98 (= 34133.31 - 8533.33 + 0)
    - {start_time: 31,999.98, start_size: 7156} # (= 8533.33 - 2133.33 + 25,599.98)
    - {start_time: 33,599.98, start_size: 7156}
    - {start_time: 33,999.98, start_size: 71560}
    - {start_time: 34,099.98, start_size: 7156}
    - {start_time: 34133.31, start_size: 71560}
```

If not would it be worth adding to the API ?
